/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2017-06-09 04:03:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.entity.RetailerMasterModel;
import com.entity.UserAccountModel;

public final class home_005fretailer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/pages/../tiles/menu.jsp", Long.valueOf(1488526778000L));
    _jspx_dependants.put("/pages/../tiles/inc.jsp", Long.valueOf(1427126852000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\n");
      out.write("<html>\n");
      out.write("<head lang=\"en\">\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>Location Based Ads</title> \r\n");
      out.write("\t<meta name=\"description\" content=\"BlackTie.co - Free Handsome Bootstrap Themes\" />\t    \r\n");
      out.write("\t<meta name=\"keywords\" content=\"themes, bootstrap, free, templates, bootstrap 3, freebie,\">\r\n");
      out.write("\t<meta property=\"og:title\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/fancybox/jquery.fancybox-v=2.1.5.css\" type=\"text/css\" media=\"screen\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/looks.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/font-awesome.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/font-awesome1.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/style1.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/font-awesome.min1.css\">\t   \r\n");
      out.write("\t\r\n");
      out.write("\t<link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,600,300,200&subset=latin,latin-ext' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"prefetch\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/images/zoom.png\">\r\n");
      out.write("\t\r\n");
      out.write("\t   \r\n");
      out.write("\t\r\n");
      out.write("<!-- \t\t<!-- SCRIPTS -->\r\n");
      out.write("<!-- \t\t<script type=\"text/javascript\" -->\r\n");
      out.write("<!-- \tsrc=\"http://maps.google.com/maps/api/js?sensor=false&libraries=places\"></script> -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/html5shiv.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/theme/fancybox/jquery.fancybox.pack-v=2.1.5.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/script.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- fancybox init -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tvar scrollToElement = function(el, ms) {\r\n");
      out.write("\r\n");
      out.write("\t\tvar speed = (ms) ? ms : 600;\r\n");
      out.write("\t\t$('html,body').animate({\r\n");
      out.write("\t\t\tscrollTop : $(el).offset().top\r\n");
      out.write("\t\t}, speed);\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");

	String upArrow="<a href='#' onclick='fnTop();' ><img src='"+request.getContextPath()+"/theme/images/up1.png' style='width: 25px;height: 25px;'/></a>";
	
	  
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\r\n");
      out.write("\r\n");

	String home="home_retailer.jsp";
String name="Home";
if(session.getAttribute("USER_MODEL")!=null){
	Object o=session.getAttribute("USER_MODEL");
	if(o instanceof UserAccountModel){
		UserAccountModel um=(UserAccountModel)session.getAttribute("USER_MODEL");
		
		name="Welcome "+um.getUsername();
	
	}else if(o instanceof RetailerMasterModel){
		RetailerMasterModel um=(RetailerMasterModel)session.getAttribute("USER_MODEL");
		name=um.getShopname();
	}
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div  data-activeslide=\"1\" style=\"background-color: #ff432e;\" >\r\n");
      out.write("<div class=\"row\"  style=\"background-color: #ff432e\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div  style=\"margin-top: 1px;width: 90%\" style=\"background-color: #ff432e\">\r\n");
      out.write("\t\t<h4 style=\"text-transform: capitalize;font-size: 18px;\">&nbsp;&nbsp; ");
      out.print(name );
      out.write("</h4>\r\n");
      out.write("\t\t</div>          \r\n");
      out.write("<!-- \t\t\t<div class=\"col-8\"> -->   \r\n");
      out.write("<!-- \t\t\t\t.navbar-toggle is used as the toggle for collapsed navbar content -->\r\n");
      out.write("<!-- \t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" -->\r\n");
      out.write("<!-- \t\t\t\t\tdata-target=\".navbar-responsive-collapse\" style=\"left: 60px;\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span -->\r\n");
      out.write("<!-- \t\t\t\t\t\tclass=\"icon-bar\"></span> -->\r\n");
      out.write("<!-- \t\t\t\t</button> -->\r\n");
      out.write("<!-- \t\t\t</div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t<div class=\"nav-collapse collapse navbar-responsive-collapse\"> -->\r\n");
      out.write("<!-- \t\t\t\t<ul class=\"nav row\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t<li data-slide=\"1\" class=\"col-12 col-sm-2\"><a id=\"menu-link-1\" href=\"#slide-1\" title=\"Next Section\"><span class=\"icon icon-home\"></span> <span class=\"text\">HOME</span></a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t<li data-slide=\"2\" class=\"col-12 col-sm-2\"><a id=\"menu-link-2\" href=\"#slide-2\" title=\"Next Section\"><span class=\"icon icon-user\"></span> <span class=\"text\">ABOUT US</span></a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t<li data-slide=\"3\" class=\"col-12 col-sm-2\"><a id=\"menu-link-3\" href=\"#slide-3\" title=\"Next Section\"><span class=\"icon icon-briefcase\"></span> <span class=\"text\">PORTFOLIO</span></a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t<li data-slide=\"4\" class=\"col-12 col-sm-2\"><a id=\"menu-link-4\" href=\"#slide-4\" title=\"Next Section\"><span class=\"icon icon-gears\"></span> <span class=\"text\">PROCESS</span></a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t<li data-slide=\"5\" class=\"col-12 col-sm-2\"><a id=\"menu-link-5\" href=\"#slide-5\" title=\"Next Section\"><span class=\"icon icon-heart\"></span> <span class=\"text\">CLIENTS</span></a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t<li data-slide=\"6\" class=\"col-12 col-sm-2\"><a id=\"menu-link-6\" href=\"#slide-6\" title=\"Next Section\"><span class=\"icon icon-envelope\"></span> <span class=\"text\">CONTACT</span></a></li> -->\r\n");
      out.write("<!-- \t\t\t\t</ul> -->\r\n");
      out.write("<!-- \t\t\t\t<div class=\"row\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t<div class=\"col-sm-2 active-menu\"></div> -->\r\n");
      out.write("<!-- \t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t</div> -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write("\n");
      out.write("\t\n");
      out.write("\t<div class=\"slide story\" id=\"slide-1\" data-slide=\"1\" style=\"background-color: black;margin: 0px;padding: 0px;\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div id=\"home-row-1\" class=\"row clearfix\">\n");
      out.write("\t\t\t\t<div class=\"col-12\">\n");
      out.write("\t\t\t\t\t<h1 class=\"font-semibold\" >\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</h1>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"row content-row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"row subtitle-row \"  style=\"padding: 0px;margin: 0px;\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-6\" >\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-item blue\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/postAds.jsp\"> <i class=\"fa fa-magic\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\tPost Ads\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-6\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-item green\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/viewOffersCustomer.jsp?productType=getRetailerAds\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t> <i class=\"fa fa-magic\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>View Ads</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"row subtitle-row\" style=\"padding: 0px;margin: 0px;\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-6\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-item light-red\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/generateReport.jsp?type=2\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-toggle=\"modal\"> <i class=\"fa fa-user\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>View Viewers</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-6\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-item color responsive\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/wishlist.jsp\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-toggle=\"modal\"> <i class=\"fa fa-user\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Update Products</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"row subtitle-row\"  style=\"padding: 0px;margin: 0px;\">\n");
      out.write("<!-- \t\t\t\t\t\t\t<div class=\"col-6\"> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<div class=\"menu-item light-orange responsive-2\"> -->\n");
      out.write("\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t\tdata-toggle=\"modal\"> <i class=\"fa fa-envelope-o\"></i> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t\t<p> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t\t\tEdit Profile  -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t\t</p> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t</a> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t</div> -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- \t\t\t\t\t\t\t</div> -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-6\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"menu-item green\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a data-toggle=\"modal\" href=\"");
      out.print(request.getContextPath());
      out.write("/tiles/ajax.jsp?methodId=logout\"> <i\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-envelope-o\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Logout</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- /row -->\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- /col-12 -->\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- /row -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- /container -->\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- /slide1 -->\n");
      out.write("\t</div>\n");
      out.write("\t<!-- === Slide 5 === -->\n");
      out.write("\t<div class=\"slide story\" id=\"slide-5\" data-slide=\"5\" style=\"display: none;\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t</div><!-- /container -->\n");
      out.write("\t</div><!-- /slide5 -->\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
