/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2017-06-08 19:36:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLDecoder;
import com.helper.StringHelper;
import com.entity.RetailerMasterModel;
import com.entity.UserAccountModel;
import com.entity.AdvertisementModel;
import java.util.ArrayList;
import java.util.Date;
import com.database.ConnectionManager;

public final class uploadPhoto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/displaytag-12.tld", Long.valueOf(1416918356000L));
    _jspx_dependants.put("/pages/../tiles/inc.jsp", Long.valueOf(1427126852000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head lang=\"en\">\r\n");
      out.write("<!-- <meta http-equiv=\"refresh\" content=\"5\"> -->\r\n");
      out.write("\t");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>Location Based Ads</title> \r\n");
      out.write("\t<meta name=\"description\" content=\"BlackTie.co - Free Handsome Bootstrap Themes\" />\t    \r\n");
      out.write("\t<meta name=\"keywords\" content=\"themes, bootstrap, free, templates, bootstrap 3, freebie,\">\r\n");
      out.write("\t<meta property=\"og:title\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/fancybox/jquery.fancybox-v=2.1.5.css\" type=\"text/css\" media=\"screen\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/looks.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/font-awesome.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/font-awesome1.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/style1.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/font-awesome.min1.css\">\t   \r\n");
      out.write("\t\r\n");
      out.write("\t<link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,600,300,200&subset=latin,latin-ext' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"prefetch\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/images/zoom.png\">\r\n");
      out.write("\t\r\n");
      out.write("\t   \r\n");
      out.write("\t\r\n");
      out.write("<!-- \t\t<!-- SCRIPTS -->\r\n");
      out.write("<!-- \t\t<script type=\"text/javascript\" -->\r\n");
      out.write("<!-- \tsrc=\"http://maps.google.com/maps/api/js?sensor=false&libraries=places\"></script> -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/html5shiv.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/theme/fancybox/jquery.fancybox.pack-v=2.1.5.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/script.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- fancybox init -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tvar scrollToElement = function(el, ms) {\r\n");
      out.write("\r\n");
      out.write("\t\tvar speed = (ms) ? ms : 600;\r\n");
      out.write("\t\t$('html,body').animate({\r\n");
      out.write("\t\t\tscrollTop : $(el).offset().top\r\n");
      out.write("\t\t}, speed);\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");

	String upArrow="<a href='#' onclick='fnTop();' ><img src='"+request.getContextPath()+"/theme/images/up1.png' style='width: 25px;height: 25px;'/></a>";
	
	  
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("     \r\n");
      out.write("<body style=\"background-color:black;;\">\r\n");

	String adTitle = StringHelper.n2s(request.getParameter("adTitle"));
try{
	adTitle=URLDecoder.decode(adTitle);
}catch(Exception e){
	
}
	String adId = StringHelper.n2s(request.getParameter("adId"));

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t   \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- === Slide 2 === -->\r\n");
      out.write("\t<div class=\"slide story\" id=\"slide-ads\" data-slide=\"2\" style=\"\tbackground-color: #1ABC9C;\tcolor: #000000;\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<h1 class=\"font-semibold\" style=\"margin-top: 0px;\"> <a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/postAds.jsp\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/theme/images/home.png\"/></a>View Ads</h1>\r\n");
      out.write("\t\t\t\t<!-- \t\t\taction=\"javascript:fnUpdate();\" -->\t\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<form id=\"login-form\" action=\"");
      out.print(request.getContextPath());
      out.write("/tiles/ajax.jsp?methodId=uploadPhoto\" \r\n");
      out.write("\t\t\t target=\"targetFrame\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t<div class=\"row\" style=\"margin:auto;width: 80%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("<!-- adsId, adsDesc, retailerId, adTitle, product, fdate, tdate, advDate -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\" style=\"margin: auto;\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\" style=\"margin-left: 2px; margin-right: 2px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"name\">Advertisment Title</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h2>");
      out.print(adTitle);
      out.write("</h2>  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"adId\" id=\"adId\" value=\"");
      out.print(adId);
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"name\">Image: <input type=\"file\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"uploaded_file\" tabindex=\"9\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"javascript:window.ActivityObject.openFile();\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Select Image\" name=\"uploaded_file\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t /></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>    \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\" style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp; <input type=\"submit\" id=\"ResetBtnId\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-success pull-center\" value=\"Upload File\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- === Arrows === -->  \r\n");
      out.write("\t\t\t\t\t\t\t<BR>   \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>   \r\n");
      out.write("\t\t</div><!-- /container -->\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<iframe id=\"targetFrame\" style=\"border: none;height: 40px;\"  name=\"targetFrame\"></iframe>\r\n");
      out.write("\t</div><!-- /slide2 -->\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function fnUpdate(){\r\n");
      out.write("\talert(str);  \r\n");
      out.write("\tftype= $('#ftype').val();\r\n");
      out.write("\t \r\n");
      out.write("\r\n");
      out.write("\turl='");
      out.print(request.getContextPath());
      out.write("/tiles/ajax.jsp?methodId=uploadPhoto',\r\n");
      out.write("\tstr=$('#login-form').serialize();\r\n");
      out.write("\t//alert(str);  \r\n");
      out.write("str=window.ActivityObject.uploadFile(url,str,\"jpg\");\r\n");
      out.write("if(str.length>0){\r\n");
      out.write("\talert(str);  \r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
