/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2017-06-09 04:32:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.HashMap;
import com.entity.UserAccountModel;
import com.entity.RetailerMasterModel;
import com.constant.ServerConstants;
import com.helper.StringHelper;
import com.entity.AdvertisementModel;
import java.util.ArrayList;
import java.util.Date;
import com.database.ConnectionManager;

public final class viewOffersCustomer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/displaytag-12.tld", Long.valueOf(1416918356000L));
    _jspx_dependants.put("/pages/../tiles/inc.jsp", Long.valueOf(1427126852000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head lang=\"en\">\n");
      out.write("<!-- <meta http-equiv=\"refresh\" content=\"5\"> -->\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>Location Based Ads</title> \r\n");
      out.write("\t<meta name=\"description\" content=\"BlackTie.co - Free Handsome Bootstrap Themes\" />\t    \r\n");
      out.write("\t<meta name=\"keywords\" content=\"themes, bootstrap, free, templates, bootstrap 3, freebie,\">\r\n");
      out.write("\t<meta property=\"og:title\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/fancybox/jquery.fancybox-v=2.1.5.css\" type=\"text/css\" media=\"screen\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/looks.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/font-awesome.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/font-awesome1.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/style1.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/font-awesome.min1.css\">\t   \r\n");
      out.write("\t\r\n");
      out.write("\t<link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,600,300,200&subset=latin,latin-ext' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"prefetch\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/images/zoom.png\">\r\n");
      out.write("\t\r\n");
      out.write("\t   \r\n");
      out.write("\t\r\n");
      out.write("<!-- \t\t<!-- SCRIPTS -->\r\n");
      out.write("<!-- \t\t<script type=\"text/javascript\" -->\r\n");
      out.write("<!-- \tsrc=\"http://maps.google.com/maps/api/js?sensor=false&libraries=places\"></script> -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/html5shiv.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/theme/fancybox/jquery.fancybox.pack-v=2.1.5.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/script.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- fancybox init -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tvar scrollToElement = function(el, ms) {\r\n");
      out.write("\r\n");
      out.write("\t\tvar speed = (ms) ? ms : 600;\r\n");
      out.write("\t\t$('html,body').animate({\r\n");
      out.write("\t\t\tscrollTop : $(el).offset().top\r\n");
      out.write("\t\t}, speed);\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");

	String upArrow="<a href='#' onclick='fnTop();' ><img src='"+request.getContextPath()+"/theme/images/up1.png' style='width: 25px;height: 25px;'/></a>";
	
	  
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\n");
      out.write("<style>\n");
      out.write("#popup_box,#popup_box2 {\n");
      out.write("\tdisplay: none;\n");
      out.write("\tposition: fixed;\n");
      out.write("\t_position: absolute;\n");
      out.write("\theight: 200px;\n");
      out.write("\twidth: 200px;\n");
      out.write("\tbackground-color: #1ABC9C;\n");
      out.write("\tcolor: #000000; \"\n");
      out.write("\tleft:;\n");
      out.write("\ttop: 150px;\n");
      out.write("\tz-index: 100;\n");
      out.write("\tmargin-left: 5px;\n");
      out.write("\tborder: 2px solid #0000FF;\n");
      out.write("\tpadding: 5px;\n");
      out.write("\tfont-size: 12px;\n");
      out.write("\t-moz-box-shadow: 0 0 5px #0000FF;\n");
      out.write("\t-webkit-box-shadow: 0 0 5px #0000FF;\n");
      out.write("\tbox-shadow: 0 0 5px #0000FF;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#popupBoxClose,#popupBoxClose2 {\n");
      out.write("\tfont-size: 12px;\n");
      out.write("\tline-height: 15px;\n");
      out.write("\tright: 15px;\n");
      out.write("\ttop: 15px;\n");
      out.write("\tposition: absolute;\n");
      out.write("\tcolor: #6fa5e2;\n");
      out.write("\tfont-weight: 500;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body style=\"background-color: black;\">\n");
      out.write("\t");

		String type = StringHelper.n2s(request.getParameter("productType"));
		String productId = StringHelper.n2s(request.getParameter("productId"));
		String latlng = StringHelper.n2s(request.getParameter("latlng"));
		System.out.println("LatLong: "+latlng);
		String KMs = StringHelper.n2s(request.getParameter("KMs"));
		String address = "";
		
		if (latlng.length() == 0) {
			latlng = StringHelper.n2s(session.getAttribute("latlong"));
			address = StringHelper.n2s(session.getAttribute("address"));
		}
		
		if (KMs.length() > 0) {
			ServerConstants.RADIUS = StringHelper.n2i(KMs);
		} else {
			KMs = "0";
		}
		
		String refreshURL = request.getContextPath()
				+ "/pages/viewOffersCustomer.jsp?latlng=" + latlng
				+ "&productType=" + type + "&productId=" + productId;

		String refreshURLWithoutProductId = request.getContextPath()
				+ "/pages/viewOffersCustomer.jsp?latlng=" + latlng
				+ "&productType=" + type;
		
		String retailerId = "2";
		String home = "home_retailer.jsp";
		
		if (session.getAttribute("USER_MODEL") != null) {
			
			Object o = session.getAttribute("USER_MODEL");
			if (o instanceof RetailerMasterModel) {
				
				RetailerMasterModel um = (RetailerMasterModel) session.getAttribute("USER_MODEL");
				retailerId = um.getRetailerId();
				home = "home_retailer.jsp";
			} else if (o instanceof UserAccountModel) {
				
				UserAccountModel um = (UserAccountModel) session.getAttribute("USER_MODEL");
				retailerId = um.getUserid();
				if (um.getRoleId().equalsIgnoreCase("A")) {
					home = "home_admin.jsp";
				} else {
					home = "home_customer.jsp";
				}
			}
		}
		HashMap wishList = ConnectionManager.getWishList(retailerId);
	
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- === Slide 2 === -->\n");
      out.write("\t<div class=\"slide story\" id=\"slide-ads\" data-slide=\"2\"\n");
      out.write("\t\tstyle=\"background-color: #1ABC9C; color: #000000;\">\n");
      out.write("\t\t<form id=\"ads-form\" action=\"javascript:fnPostAds();\">\n");
      out.write("\t\t\t<h1 class=\"font-semibold\" style=\"margin-top: 0px;\">\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/");
      out.print(home);
      out.write("\"><img\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/theme/images/home.png\" /></a>View Ads\n");
      out.write("\t\t\t</h1>\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\"\n");
      out.write("\t\t\t\t\tstyle=\"margin: auto; width: 80%; border-style: solid; border-width: thin; border-bottom-style: none; padding: 5px;\">\n");
      out.write("\t\t\t\t\t<div class=\"col-12 col-sm-3\">\n");
      out.write("\t\t\t\t\t\t<h4 class=\"font-semibold\">Search Here:</h4>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-12 col-sm-3\">\n");
      out.write("\t\t\t\t\t\t<select name=\"productId\" id=\"productId\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\" selected=\"selected\">Search Product</option>\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(ConnectionManager.getCombo("SELECT productId as `key`, productName as `value` FROM products"));
      out.write("\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-12 col-sm-3\">\n");
      out.write("\t\t\t\t\t\t<select name=\"KMs\" id=\"KMs\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\" selected=\"selected\">Search Radius</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"5\">5 KM</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"10\">10 KM</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"20\">20 KM</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"30\">30 KM</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"60\">60 KM</option>\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-12 col-sm-3\">\n");
      out.write("\t\t\t\t\t\t<a id=\"ResetBtnId\" style=\"background-color: black;\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-danger pull-right\" href=\"#\" onclick=\"fnSearch();\">Search</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- /container -->\n");
      out.write("\t\t\t\t<div class=\"row\" style=\"margin: auto; width: 80%\">\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\n");
      out.write("\t\t\t\t\t\t<!-- adsId, adsDesc, retailerId, adTitle, product, fdate, tdate, advDate -->\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\" style=\"margin: auto;\">\n");
      out.write("\t\t\t\t\t\t\t");

								ArrayList ads = null;
								if (type.equalsIgnoreCase("products")) {
									
									ads = ConnectionManager.getProductWiseAds(productId);
								} else if (type.equalsIgnoreCase("myLocation")) {
									ads = ConnectionManager.getProductWiseAds(latlng.split(",")[0],
											latlng.split(",")[1]);
								} else if (type.equalsIgnoreCase("myLocationProducts")) {
									ads = ConnectionManager.getProductWiseAds(productId,
											latlng.split(",")[0], latlng.split(",")[1]);
								} else if (type.equalsIgnoreCase("getRetailerAds")) {
									ads = ConnectionManager.getAdvertisements(retailerId);
								}

								else {
									ads = ConnectionManager.getProductWiseAdsAll();
								}

								session.setAttribute("ADS", ads);
								for (int i = 0; ads != null && i < ads.size(); i++) {
									AdvertisementModel am = (AdvertisementModel) ads.get(i);
									String wishL = StringHelper
											.n2s(wishList.get(am.getAdsId() + ""));
									String style = "";
									String name = "star.png";
									if (wishL.length() > 0) {
										style = "color:blue;";
										name = "star2.png";
									}
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row subtitle-row\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border-style: solid; border-width: thin; border-bottom-style: none; padding: 5px;\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-2 col-sm-2\" style=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"home-hover navigation-slide\" data-slide=\"4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/tiles/ajax.jsp?methodId=downloadImage&imageId=");
      out.print(am.getAdsId());
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\talt=\"No Image\" style=\"width: 50px; height: 50px;\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-10 col-sm-10 font-light\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 18px;");
      out.print(style);
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<B>");
      out.print(am.getAdTitle());
      out.write("</B><BR> <span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 14px;\">");
      out.print(am.getAdsDesc());
      out.write('-');
      out.write('[');
      out.print(am.getTdate());
      out.write("]</span><BR>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span style=\"font-size: 14px;\"> <a href=\"#\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"fnShowDirections('");
      out.print(am.getShopLat());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(am.getShopLng());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(am.getShopaddress());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(am.getShopname());
      out.write("')\"><img\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/theme/images/directions.png\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"fnShow('");
      out.print(am.getAdsId());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(am.getShopname());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(am.getShopaddress());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(am.getOwnername());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(am.getPhone());
      out.write("');\"><img\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/theme/images/info.png\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" title=\"Add to Wishlist\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"fnAddWishlist('");
      out.print(am.getAdsId());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(retailerId);
      out.write("');\"><img\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/theme/images/");
      out.print(name);
      out.write("\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- /row -->\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\" style=\"margin: auto;\">\n");
      out.write("\t\t\t\t\t\t\t<a type=\"reset\" id=\"ResetBtnId\" style=\"background-color: black;\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-danger pull-right\"\n");
      out.write("\t\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/pages/");
      out.print(home);
      out.write("\">Main\n");
      out.write("\t\t\t\t\t\t\t\tMenu</a> &nbsp;&nbsp; <a id=\"ResetBtnId\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"background-color: black;\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-danger pull-right\" href=\"");
      out.print(refreshURL);
      out.write("\">Refresh</a>\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&nbsp;\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- === Arrows === -->\n");
      out.write("\t\t\t\t\t\t<BR>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- /container -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t<div id=\"popup_box2\" name=\"popup_box2\"\n");
      out.write("\t\t\t\t\tstyle=\"display: none; z-index: 9999;\">\n");
      out.write("\t\t\t\t\t<span id=\"popup_text2\"> </span> <a id=\"popupBoxClose2\"><img\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/theme/images/CloseButton.png\"\n");
      out.write("\t\t\t\t\t\tonclick=\"$('#popup_box2').fadeOut('slow');\" /> </a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- /slide2 -->\n");
      out.write("\n");
      out.write("\t<script>\n");
      out.write("function fnShowDirections(lat,lng,addr,name){\n");
      out.write("\twindow.ActivityObject.showDirections(lat,lng,addr,name);\n");
      out.write("}\n");
      out.write("function fnShow(adId,shopName,shopAddress,owner,phone){\n");
      out.write("\t$('#popup_box2').show();\n");
      out.write("\t$('#popup_text2').html('<h3>'+shopName+'</h3><BR><span>'+owner+'</span><BR><span>'+shopAddress+'</span><BR><span>'+phone+'</span>');\n");
      out.write("\tfnAddAdView(adId);\n");
      out.write("}\n");
      out.write("function fnAddWishlist(adsId,userId){\n");
      out.write("\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/tiles/ajax.jsp?methodId=insertWishlist\",\n");
      out.write("\t\t\t'adsId='+adsId+\"&userId=\"+userId,\n");
      out.write("\t\t\tfunction(data) {\n");
      out.write("\t\tdata=$.trim(data);\n");
      out.write("\t\talert('Added to whishlist');\n");
      out.write("\n");
      out.write("\t\t\t});\n");
      out.write("}\n");
      out.write("function fnSearch(){\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\twindow.location.href='");
      out.print(refreshURLWithoutProductId);
      out.write("&productId='+$('#productId').val()+'&KMs='+$('#KMs').val();\n");
      out.write("}\n");
      out.write("function fnPostAds() {\n");
      out.write("\t\t var str = $( \"#ads-form\" ).serialize();\n");
      out.write("\t\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/tiles/ajax.jsp?methodId=fnPostAds\",\n");
      out.write("\t\t\t\tstr,\n");
      out.write("\t\t\t\tfunction(data) {\n");
      out.write("\t\t\tdata=$.trim(data);\n");
      out.write("\t\t\talert(data);\n");
      out.write("\t\t\t$( \"#ads-form\" )[0].reset();\n");
      out.write("\t\t\t\t});\n");
      out.write("}\n");
      out.write("function fnAddAdView(adId) {\n");
      out.write("\t var str = $( \"#ads-form\" ).serialize();\n");
      out.write("\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/tiles/ajax.jsp?methodId=addView\",\n");
      out.write("\t\t\t'reatailerId=");
      out.print(retailerId);
      out.write("&adId='+adId,\n");
      out.write("\t\t\tfunction(data) {\n");
      out.write("\t\tdata=$.trim(data);\n");
      out.write("\t\t//alert('');\n");
      out.write("\t\t});\n");
      out.write("}\n");
      out.write("function fnDeleteAds(adsId) {\n");
      out.write("\t if(confirm('Are you sure?')){\n");
      out.write("\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/tiles/ajax.jsp?methodId=fnDeleteAds\",\n");
      out.write("\t\t\t'adsId='+adsId,\n");
      out.write("\t\t\tfunction(data) {\n");
      out.write("\t\talert('Ad Has Been deleted');\n");
      out.write("\t\t\n");
      out.write("\t\t\t});\n");
      out.write("\t }\n");
      out.write("}\n");
      out.write("$('#productId').val('");
      out.print(productId);
      out.write("');\n");
      out.write("$('#KMs').val('");
      out.print(KMs);
      out.write("');\n");
      out.write("\t\tfunction fnGetLocation() {\n");
      out.write("\t\t\ttry {\n");
      out.write("\t\t\t\tstr = window.ActivityObject.getLocation();\n");
      out.write("\t\t\t\tif (str.indexOf('#') != -1) {\n");
      out.write("\t\t\t\t\tlatlong = str.substring(0, str.indexOf('#'));\n");
      out.write("\t\t\t\t\taddress = str.substring(str.indexOf('#') + 1);\n");
      out.write("\t\t\t\t\treturn [ latlong, address ];\n");
      out.write("\t\t\t\t\t//$('#startlocation').val(str);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t} catch (err) {\n");
      out.write("\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\treturn \"\";\n");
      out.write("\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
